### ISSUE TITLE
Typing Injected Dialog Data causes compile error with aot

### ISSUE THREAD

**Issue by jonathanRinciari** [angular/components#15862]
#### What is the expected behavior?
Compiles successfully

#### What is the current behavior?

`Metadata collected contains an error that will be reported at runtime: Expression form not supported.`

#### What are the steps to reproduce?
Create a dialog component that receives data from the caller. Typing the data will result in an error.

`
@Inject(MAT_DIALOG_DATA) public data: {user: User};
`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`
    "@angular/common": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/material": "^7.3.7",
    "@angular/cdk": "^7.3.7",
`

#### Is there anything else we should know?
Workaround is to remove the typing or add a // @dynamic about the component decorator.

**Comment by jelbourn** [comment]
@jonathanRinciari can you share a more complete reproduction? We use AOT exclusively for apps inside Google and have not seen this issue.

**Comment by jonathanRinciari** [comment]
Sure! I should have mentioned before but this is in a library using ng-packager.

`
export class EditUserComponent implements OnInit {
  constructor(
    private matDialogRef: MatDialogRef<EditUserComponent>,
    private matDialog: MatDialog,
    @Inject(MAT_DIALOG_DATA) public data: any,
  ) {
    if (data.user) {
      this.user = data.user;
    } else {
      this.close({isSaving: false});
    }
  }
}
`
- Simple dialog component with injecting data from the caller. _This will work fine_, because the type of data is any.

`
export class EditUserComponent implements OnInit {
  constructor(
    private matDialogRef: MatDialogRef<EditUserComponent>,
    private matDialog: MatDialog,
    @Inject(MAT_DIALOG_DATA) public data: {user: User},
  ) {
    if (data.user) {
      this.user = data.user;
    } else {
      this.close({isSaving: false});
    }
  }
}
`
- Same as the previous version the only different is the type is specified as having a property user of type User. _This approach will not compile_.

`
interface DialogData {
   user: User;
}
export class EditUserComponent implements OnInit {
  constructor(
    private matDialogRef: MatDialogRef<EditUserComponent>,
    private matDialog: MatDialog,
    @Inject(MAT_DIALOG_DATA) public data: DialogData,
  ) {
    if (data.user) {
      this.user = data.user;
    } else {
      this.close({isSaving: false});
    }
  }
}
`

- This approach declares an interface with a property user of type User. _This approach will work_


The error when trying to build the library will kick out the following error..

`
BUILD ERROR
/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/projects/component-library/src/lib/components/edit-user/edit-user-dialog.component.ts:24:1: Error encountered in metadata generated for exported symbol 'EditUserComponent':
 /Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/projects/component-library/src/lib/components/edit-user/edit-user-dialog.component.ts:38:43: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":37,"character":42}
Error: /Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/projects/component-library/src/lib/components/edit-user/edit-user-dialog.component.ts:24:1: Errorencountered in metadata generated for exported symbol 'EditUserComponent':
 /Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/projects/component-library/src/lib/components/edit-user/edit-user-dialog.component.ts:38:43: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":37,"character":42}
    at /Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler-cli/src/metadata/collector.js:708:31
    at Array.forEach (<anonymous>)
    at validateMetadata (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler-cli/src/metadata/collector.js:696:46)
    at MetadataCollector.getMetadata (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler-cli/src/metadata/collector.js:551:21)
    at MetadataCache.getMetadata (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler-cli/src/transformers/metadata_cache.js:87:41)
    at Object.getSourceFileMetadata (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:117:56)
    at Object.readMetadata (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:46:37)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:469:38)
    at StaticSymbolResolver.getModuleMetadata (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler/bundles/compiler.umd.js:22051:49)
    at StaticSymbolResolver.hasDecorators (/Users/jon/Code/blogs/angular/gcv-components/gcv-component-library/node_modules/@angular/compiler/bundles/compiler.umd.js:21809:33)
`

- The formatting here is probably easier to parse out.

[https://gist.github.com/jonathanRinciari/1bff494502a4a6032773a175f350d6b0](url)

**Comment by alvaromartmart** [comment]
I have found the same issue in my project.

**Comment by StewartSnow** [comment]
Seeing the same issue over here too

**Comment by puku0x** [comment]
I'm facing a similar issue not only AOT but also JIT.

```
Angular CLI: 8.0.4
Node: 10.15.1
OS: darwin x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cdk                      8.0.1
@angular/cli                      8.0.4
@angular/material                 8.0.1
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

```ts
import { Component, ChangeDetectionStrategy, Inject } from '@angular/core';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';

interface DialogData {
  id: string;
}

@Component({
  selector: 'app-todo-delete-dialog',
  templateUrl: './todo-delete-dialog.component.html',
  styleUrls: ['./todo-delete-dialog.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TodoDeleteDialogComponent {
  constructor(
    @Inject(MAT_DIALOG_DATA) private data: DialogData
  ) {}
}
```
```
core.js:7187 ERROR Error: Uncaught (in promise): ReferenceError: DialogData is not defined
ReferenceError: DialogData is not defined
    at push../src/app/todo/containers/todo-delete-dialog/todo-delete-dialog.component.ts.TodoDeleteDialogComponent.ctorParameters (todo-delete-dialog.component.ts:22)
    at ReflectionCapabilities._ownParameters (core.js:757)
    at ReflectionCapabilities.parameters (core.js:782)
    at JitReflector.parameters (platform-browser-dynamic.js:48)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:19929)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:19882)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:19511)
    at CompileMetadataResolver._getEntryComponentMetadata (compiler.js:20081)
    at compiler.js:19738
    at Array.map (<anonymous>)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:30885)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
```

**Comment by bigozzi-inspect** [comment]
I have the same problem

**Comment by ErgoSoftUK** [comment]
Skip the injection and set your data manually via the reference component instance (before subscribing).  You could even wrap the whole thing with a static helper.

```javascript
export class EditUserComponent implements OnInit {
  static open(dialog: MatDialog, data: DialogData) {
    let dialogRef = dialog.open(EditUserComponent, {disableClose: true});
    dialogRef.componentInstance.data = data;
    return dialogRef.afterClosed();
  }

  data: DialogData;

  constructor(
    private matDialogRef: MatDialogRef<EditUserComponent>,
    private matDialog: MatDialog
  ) {
  }
}
```
then call from your component...
```javascript
  EditUserComponent.open(this.dialog, <dialog data>).subscribe(
    (result) => <do something>,
    (error) => <do something else>
  );
```

**Comment by devversion** [comment]
Hello! I just tried this with a new CLI library. I don't seem to be able to run into an error and if there would be one, then that would be a framework bug. If `@Inject` is specified, the parameter type is not of interest for the Angular compiler.
