### ISSUE TITLE
Bazel issues when trying to run the test suite on Windows

### ISSUE THREAD

**Issue by ramarivera** [angular/components#16632]
#### What is the expected behavior?
The tests should run without failing 

#### What is the current behavior?

```
PS C:\DEV\components> yarn run test
yarn run v1.15.2
$ bazel test //src/... --test_tag_filters=-e2e,-browser:firefox-local --build_tag_filters=-browser:firefox-local --build_tests_only
DEBUG: C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:256:5: rbe_default is using checked-in configs 'struct(config_repos = [], create_cc_configs = True, create_java_configs = True, env = {"ABI_LIBC_VERSION": "glibc_2.19", "ABI_VERSION": "clang", "BAZEL_COMPILER": "clang", "BAZEL_HOST_SYSTEM": "i686-unknown-linux-gnu", "BAZEL_TARGET_CPU": "k8", "BAZEL_TARGET_LIBC": "glibc_2.19", "BAZEL_TARGET_SYSTEM": "x86_64-unknown-linux-gnu", "CC": "clang", "CC_TOOLCHAIN_NAME": "linux_gnu_x86"}, java_home = "/usr/lib/jvm/java-8-openjdk-amd64", name = "9.0.0")'
INFO: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_tools/tools/build_defs/repo/git.bzl:252:18):
 - C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - C:/dev/components/WORKSPACE:94:1
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_docker':
   Traceback (most recent call last):
        File "C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("bash" -c "
cd C:/users/rrivera/_bazel_rrivera/ylcne4dw/external
set -ex
( cd C:/users/rrivera/_bazel_rrivera/ylcne4dw/external &&
    if ! ( cd 'C:/users/rrivera/_bazel_rrivera/ylcne4dw/external(...)): The system cannot find the file specified.
INFO: Call stack for the definition of repository 'org_chromium_chromedriver' which is a platform_http_file (rule definition at C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/io_bazel_rules_webtesting/web/internal/platform_http_file.bzl:52:22):
 - C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/npm_bazel_karma/browser_repositories.bzl:56:5
 - C:/dev/components/WORKSPACE:72:1
INFO: Call stack for the definition of repository 'org_chromium_chromium' which is a platform_http_file (rule definition at C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/io_bazel_rules_webtesting/web/internal/platform_http_file.bzl:52:22):
 - C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/npm_bazel_karma/browser_repositories.bzl:23:5
 - C:/dev/components/WORKSPACE:72:1
ERROR: While resolving toolchains for target @bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main: invalid registered toolchain '@io_bazel_rules_docker//toolchains/docker:default_linux_toolchain': no such package '@io_bazel_rules_docker//toolchains/docker': Traceback (most recent call last):
        File "C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("bash" -c "
cd C:/users/rrivera/_bazel_rrivera/ylcne4dw/external
set -ex
( cd C:/users/rrivera/_bazel_rrivera/ylcne4dw/external &&
    if ! ( cd 'C:/users/rrivera/_bazel_rrivera/ylcne4dw/external(...)): The system cannot find the file specified.
ERROR: Analysis of target '//src/cdk-experimental/dialog:unit_tests_chromium-local' failed; build aborted: invalid registered toolchain '@io_bazel_rules_docker//toolchains/docker:default_linux_toolchain': no such package '@io_bazel_rules_docker//toolchains/docker': Traceback (most recent call last):
        File "C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/rrivera/_bazel_rrivera/ylcne4dw/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("bash" -c "
cd C:/users/rrivera/_bazel_rrivera/ylcne4dw/external
set -ex
( cd C:/users/rrivera/_bazel_rrivera/ylcne4dw/external &&
    if ! ( cd 'C:/users/rrivera/_bazel_rrivera/ylcne4dw/external(...)): The system cannot find the file specified.
INFO: Elapsed time: 1.146s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
error Command failed with exit code 1.
```

#### What are the steps to reproduce?

I just ran `yarn run test` after following the steps for setting up dev environment.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am trying to run tests on Windows 10 1809.

**Comment by ramarivera** [comment]
Hi, any update, or fixing steps/ideas on this? :)

**Comment by ogix** [comment]
I am getting a different error:

```
PS C:\Users\ogon\Documents\GitHub\angular-components> yarn run test
yarn run v1.17.3
$ bazel test //src/... --test_tag_filters=-e2e,-browser:firefox-local --build_tag_filters=-browser:firefox-local --build_tests_only
INFO: Analyzed 75 targets (1 packages loaded, 2 targets configured).
INFO: Found 75 test targets...
ERROR: C:/users/ogon/documents/github/angular-components/src/material/core/BUILD.bazel:83:1: SassCompiler src/material/core/theming/prebuilt/indigo-pink.css failed: Worker process quit or closed its stdin stream
when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(356): NativeProcess:WriteStdin(17616): The pipe is being closed.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.writeStream(WindowsSubprocess.java:263)
        at com.google.devtools.build.lib.windows.WindowsSubprocess.access$000(WindowsSubprocess.java:33)
        at com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessOutputStream.write(WindowsSubprocess.java:57)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3003)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.flush(CodedOutputStream.java:2914)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:99)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:330)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:172)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:121)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:225)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:123)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:88)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.actions.SpawnContinuation$1.execute(SpawnContinuation.java:80)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction$SpawnActionContinuation.execute(SpawnAction.java:1344)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:314)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:123)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:851)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:985)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:957)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:577)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:760)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:275)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at C:/users/ogon/_bazel_ogon/qjldwlr7/bazel-workers/worker-15-SassCompiler.log ---8<---8<---
LAUNCHER ERROR: Cannot launch process: "bash.exe" -c "C:\\\\users\\\\ogon\\\\_bazel_ogon\\\\qjldwlr7\\\\execroot\\\\angular_material\\\\bazel-out\\\\host\\\\bin\\\\external\\\\io_bazel_rules_sass\\\\sass\\\\sass
--persistent_worker"
Reason: (error: 2): The system cannot find the file specified.
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 3.528s, Critical Path: 0.14s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

It seems that the script is looking for bash.exe?

**Comment by ogix** [comment]
I've installed Windows Subsystem for Linux and the bash error disappeared but still getting similar output.

**Comment by crisbeto** [comment]
Closing since the Bazel setup has changed significantly since this was opened.
