### ISSUE TITLE
MatPaginator requires the classlist.js polyfill to work with IE11 when Ivy is enabled.

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/components#16726]
Not sure if this is a defect or a documentation issue.

MatPaginator requires the classlist.js polyfill to work with IE11 when Ivy is enabled.

This is because Ivy tries to add classes to the SVG used in the MatPaginator using el.classList.add, and that requires a polyfill to work on SVGs in IE11.

```
"TypeError: Unable to get property 'add' of undefined or null reference
   at DefaultDomRenderer2.prototype.addClass (http://127.0.0.1:8080/vendor-es5.js:77117:64)
   at BaseAnimationRenderer.prototype.addClass (http://127.0.0.1:8080/vendor-es5.js:75657:66)
   at setClass (http://127.0.0.1:8080/vendor-es5.js:34066:54)
   at renderStylingMap (http://127.0.0.1:8080/vendor-es5.js:34092:13)
   at renderInitialStyling (http://127.0.0.1:8080/vendor-es5.js:36943:1)
   at ɵɵelementStart (http://127.0.0.1:8080/vendor-es5.js:42493:1)
   at MatPaginator_Template (http://127.0.0.1:8080/vendor-es5.js:71662:5)
   at executeTemplate (http://127.0.0.1:8080/vendor-es5.js:35719:5)
   at checkView (http://127.0.0.1:8080/vendor-es5.js:36822:5)
   at componentRefresh (http://127.0.0.1:8080/vendor-es5.js:36626:5)"
```

I haven't had a chance yet to check if other components have the same issue.

NOTE: To get to this error I first had to manually strip the "use strict"; declarations from the es5 bundle (workaround for [#30569](https://github.com/angular/angular/issues/30569))

#### Reproduction

https://github.com/james-schwartzkopf/ng8-issues/tree/mat-paginator-ie11-ivy

Steps to reproduce:
1. yarn && yarn run start 
2. open http://127.0.0.1:8080/index.html in IE11
 
 #### Expected Behavior

MatPaginator should work without polyfill (at least there is no documentation indicating it is needed).

#### Actual Behavior

MatPaginator only works with classlist.js installed and imported in src/polyfill.ts
What behavior did you actually see?

#### Environment

- Angular: 8.2.0
- CDK/Material: 8.1.2
- Browser(s): IE11
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
We could get around it by changing the CSS selector a bit, but this isn't the only place where we set classes on SVG elements (e.g. `mat-progress-bar` and `mat-datepicker-toggle` have it as well). @jelbourn should we try to tackle this case in our code or recommend that people install the polyfill? It's already one of the optional polyfills in https://angular.io/guide/browser-support.

**Comment by crisbeto** [comment]
Will be resolved in core by https://github.com/angular/angular/pull/32111.
