### ISSUE TITLE
(Development) Following DEV_ENVIRONMENT.md don't work

### ISSUE THREAD

**Issue by iget-master** [angular/components#17053]
### What are you trying to do?

I'm trying to contribute with this package, but when setting up the environment as described on DEV_ENVIRONMENT.md, it don't work for a few reasons.

1. The command `yarn dev-app` doesn't exists. The correct command is `yarn demo-app`.
2. There's an error when running it:

```
/home/esoares/Sandbox/material2/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
tools/gulp/tasks/screenshots.ts (92,70): Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'. (2345)
tools/gulp/tasks/screenshots.ts (114,22): Argument of type '(childSnapshot: DataSnapshot) => void' is not assignable to parameter of type '(a: DataSnapshot) => boolean'.
  Type 'void' is not assignable to type 'boolean'. (2345)
    at getOutput (/home/esoares/Sandbox/material2/node_modules/ts-node/src/index.ts:307:15)
    at /home/esoares/Sandbox/material2/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/home/esoares/Sandbox/material2/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/home/esoares/Sandbox/material2/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/esoares/Sandbox/material2/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
error Command failed with exit code 1.
```

#### What troubleshooting steps have you tried?

I'm verified that I'm using the correct node, yarn and gulp versions, and it's OK:

    $ node -v: v10.16.3
    $ yarn -v: 1.17.3
    $ gulp -v: CLI: 1.4.0 / Local: 3.9.1

It's everything OK with my environment, unless the DEV_ENVIRONMENT.md is not updated.

#### Reproduction

Follow the DEV_ENVIRONMENT.md steps
  
#### Environment

    $ uname -a: Linux iget-esoares 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    $ node -v: v10.16.3
    $ yarn -v: 1.17.3
    $ gulp -v: CLI: 1.4.0 / Local: 3.9.1

**Comment by iget-master** [comment]
My fault. Using the wrong branch. I was on v5.x following v8 instructions. Closing it.
