### ISSUE TITLE
Stepper with target ES2015 - markForCheck Error

### ISSUE THREAD

**Issue by akvaliya** [angular/components#17075]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-evhevw

Steps to reproduce:
1. in tsconfig.json > compilerOptions > "target": "es2015"
2. In angular.json > configurations > production > "aot": false, "buildOptimizer": false
3. ng build --prod
 
#### Expected Behavior
There shouldn't be any error in console when run site

#### Actual Behavior
When open prod build For all inactive steps getting below markForCheck Error. Also when click on stepper header getting same error.

```
main-es2015.380f824f17866dab78de.js:1 ERROR TypeError: Cannot read property 'markForCheck' of undefined
    at Ol._stateChanged (5-es2015.cb1c89192b4b1b2b48d4.js:1)
    at Cl.ngOnChanges (5-es2015.cb1c89192b4b1b2b48d4.js:1)
    at main-es2015.380f824f17866dab78de.js:1
    at main-es2015.380f824f17866dab78de.js:1
    at ty (main-es2015.380f824f17866dab78de.js:1)
    at Ay (main-es2015.380f824f17866dab78de.js:1)
    at Object.eval [as updateDirectives] (Pl.ngfactory.js:393)
    at Object.updateDirectives (main-es2015.380f824f17866dab78de.js:1)
    at ey (main-es2015.380f824f17866dab78de.js:1)
    at cy (main-es2015.380f824f17866dab78de.js:1)
```

#### Environment

- Angular: ~8.2.4
- CDK/Material: ~8.2.0
- Browser(s): Chrome, Opera, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment]
I wasn't able to reproduce it by downloading it from Stackblitz, although I had to make some changes to get it to build. Can you put sample project as a repo on GitHub instead? Also I have a hunch what the issue might be. Can you also try to replace the `mat-horizontal-stepper` with a `mat-vertical-stepper` and check whether the build still fails with the same error?

**Comment by devversion** [comment]
The related issue is https://github.com/angular/components/issues/13715. I see that you posted on the other issue that the fix didn't work on your end, but I also had others reporting that the fix in framework solved the issue.

**Comment by akvaliya** [comment]
This is a repository [https://github.com/akvaliya/angular8stepper](https://github.com/akvaliya/angular8stepper) for reproducing error with `ng build --prod`.

`mat-vertical-stepper` doesn't produce errors.

**Comment by akvaliya** [comment]
@devversion It's resolved in production with AOT. But it doesn't work without AOT in production.

**Comment by khalilou88** [comment]
i have the same error and when i use aot the error disappear.

**Comment by bk-m** [comment]
@crisbeto I just ran into the same problem using Angular/Material 7 and according to your previous comment I tried swapping the horizontal stepper for a vertical one, which for some reason works. Is there some workaround to get the horizontal stepper working or is there an underlying bug that needs fixing?

**Comment by mickaeltr** [comment]
While [there does not seem to be significant changes in the stepper](https://github.com/angular/components/releases), I started seeing a similar issue, after upgrading from 10.1.2 to 10.1.3.

The web application works fine, however the TestBed now fail with the following stacktrace, when doing `fixture.detectChanges();`: 

```
TypeError: Cannot read property 'markForCheck' of undefined
    at MatHorizontalStepper.CdkStepper._stateChanged (/path/to/src/cdk/stepper/stepper.ts:397:29)
    at MatStep.CdkStep.ngOnChanges (/path/to/src/cdk/stepper/stepper.ts:236:19)
    at checkAndUpdateDirectiveInline (/path/to/packages/core/src/view/provider.ts:213:15)
    at checkAndUpdateNodeInline (/path/to/packages/core/src/view/view.ts:440:14)
    at checkAndUpdateNode (/path/to/packages/core/src/view/view.ts:400:12)
    at debugCheckAndUpdateNode (/path/to/packages/core/src/view/services.ts:433:44)
    at debugCheckDirectivesFn (/path/to/packages/core/src/view/services.ts:394:7)
    at Object.eval [as updateDirectives] (ng:///DynamicTestModule/CreateAppointmentComponent.ngfactory.js:2079:9)
    at Object.debugUpdateDirectives [as updateDirectives] (/path/to/packages/core/src/view/services.ts:388:19)
    at checkAndUpdateView (/path/to/packages/core/src/view/view.ts:370:12)
    at callViewAction (/path/to/packages/core/src/view/view.ts:626:11)
    at execComponentViewsAction (/path/to/packages/core/src/view/view.ts:570:7)
    at checkAndUpdateView (/path/to/packages/core/src/view/view.ts:381:3)
    at callWithDebugContext (/path/to/packages/core/src/view/services.ts:638:23)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (/path/to/packages/core/src/view/services.ts:349:10)
    at ViewRef_.detectChanges (/path/to/packages/core/src/view/refs.ts:284:16)
    at ComponentFixture._tick (/path/to/packages/core/testing/src/component_fixture.ts:113:28)
    at /path/to/packages/core/testing/src/component_fixture.ts:127:14
    at ZoneDelegate.invoke (/path/to/frontend/node_modules/zone.js/dist/zone.js:386:30)
    at ProxyZoneSpec.onInvoke (/path/to/frontend/node_modules/zone.js/dist/proxy.js:117:43)
    at ZoneDelegate.invoke (/path/to/frontend/node_modules/zone.js/dist/zone.js:385:36)
    at Object.onInvoke (/path/to/packages/core/src/zone/ng_zone.ts:326:29)
    at ZoneDelegate.invoke (/path/to/frontend/node_modules/zone.js/dist/zone.js:385:36)
    at Zone.run (/path/to/frontend/node_modules/zone.js/dist/zone.js:143:47)
    at NgZone.run (/path/to/packages/core/src/zone/ng_zone.ts:180:50)
    at ComponentFixture.detectChanges (/path/to/packages/core/testing/src/component_fixture.ts:126:19)
    at /path/to/frontend/src/app/components/pages/appointments/create/create-appointment.component.spec.ts:208:13
    at ZoneDelegate.invoke (/path/to/frontend/node_modules/zone.js/dist/zone.js:386:30)
    at ProxyZoneSpec.onInvoke (/path/to/frontend/node_modules/zone.js/dist/proxy.js:117:43)
    at ZoneDelegate.invoke (/path/to/frontend/node_modules/zone.js/dist/zone.js:385:36)
    at Zone.run (/path/to/frontend/node_modules/zone.js/dist/zone.js:143:47)
    at Object.wrappedFunc (/path/to/frontend/node_modules/jest-preset-angular/build/zone-patch/index.js:49:30)
    at Object.asyncJestLifecycle (/path/to/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:58:37)
    at /path/to/frontend/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (/path/to/frontend/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /path/to/frontend/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by crisbeto** [comment]
This issue is tracking the recent errors https://github.com/angular/components/issues/20271.
