### ISSUE TITLE
Exception when trying to unit-test component with MatTable inside

### ISSUE THREAD

**Issue by GaryFreeman** [angular/components#18490]
#### Reproduction

Angular application: https://stackblitz.com/edit/angular-3x2hdh
Unit tests: https://stackblitz.com/edit/angular-1ych3a

Steps to reproduce:
1. Go to the first link - application works
2. Go to the second link - the same application doesn't pass unit-test
 
 
#### Expected Behavior

There is no exception from the CdkTable.

#### Actual Behavior

CdkTable component throws an exception:
```
TypeError: Cannot read property 'viewContainer' of undefined

error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 640407585, rootNodeFlags: 1, nodeMatchedQueries: 4, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 1, childFlags: 640407585, directChildFlags: 33554433, childMatchedQueries: 4, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 37, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'div', attrs: [ Array ], template: null, componentProvider: null, componentView: null, componentRendererType: null, publicProviders: null({  }), allProviders: null({  }), handleEvent: Function }), provider: null, text: null, query: null, ngContent: null }), Object({ nodeIndex: 1, parent: Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 1, childFlags: 640407585, directChildFlags:  ...
    at <Jasmine>
    at MatTable.CdkTable._forceRenderHeaderRows (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/cdk@8.2.3/bundles/cdk-table.umd.js:2339:35)
    at MatTable.CdkTable.ngAfterContentChecked (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/cdk@8.2.3/bundles/cdk-table.umd.js:1581:18)
    at callProviderLifecycles (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:21553:22)
    at callElementProvidersLifecycles (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:21531:17)
    at callLifecycleHooksChildrenFirst (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:21521:33)
    at checkAndUpdateView (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:29558:9)
    at callViewAction (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:29795:25)
    at execEmbeddedViewsAction (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:29758:21)
    at checkAndUpdateView (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:29555:9)
    at callViewAction (https://angular-1ych3a.stackblitz.io/turbo_modules/@angular/core@8.2.14/bundles/core.umd.js:29795:25)
```

#### Environment

- Angular: 8.2.8
- CDK/Material: 8.2.1
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows and macOS

#### Comments

BTW, as I know, properties decorated with @ViewChild decorator are set just before calling ngAfterViewInit hook, but CdkTable uses that properties inside ngAfterContentChecked which is called earlier that ngAfterViewInit.

**Comment by devversion** [comment]
Thanks for this issue. Looks like you imported the table components individually, but actually you should just add `MatTableModule` to the imports in your Testbed configure call.
