### ISSUE TITLE
help(COMPONENT): I have a problem compiling (yarn build) 

### ISSUE THREAD

**Issue by chenjianlong-java** [angular/components#19684]
I have a problem compiling, the detailed error message is below, 
Both command --yarn build and command --yarn install report errors,
anyone know how to solve it?

error msg:
F:\front-end\angular-component>yarn build
yarn run v1.22.0
$ node ./scripts/build-packages-dist.js
######################################
  Building release packages...
  Compiling with Ivy: false
######################################
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository nodejs_windows_amd64 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule node_repositories_rule defined at:
  C:/users/chenjianlong/_bazel_chenjianlong/lo7ziovu/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:668:26: in <toplevel>
WARNING: Download from https://nodejs.org/dist/v12.9.1/node-v12.9.1-win-x64.zip failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'nodejs_windows_amd64':
   Traceback (most recent call last):
        File "C:/users/chenjianlong/_bazel_chenjianlong/lo7ziovu/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 662
                _download_node(repository_ctx)
        File "C:/users/chenjianlong/_bazel_chenjianlong/lo7ziovu/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 300, in _download_node
                repository_ctx.download_and_extract(<4 more arguments>)
java.io.IOException: Error downloading [https://nodejs.org/dist/v12.9.1/node-v12.9.1-win-x64.zip] to C:/users/chenjianlong/_bazel_chenjianlong/lo7ziovu/external/nodejs_windows_amd64/bin/nodejs/node-v12.9.1-win-x64.zip: connect timed out
ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': no such package '@nodejs_windows_amd64//': Traceback (most recent call last):
        File "C:/users/chenjianlong/_bazel_chenjianlong/lo7ziovu/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 662
                _download_node(repository_ctx)
        File "C:/users/chenjianlong/_bazel_chenjianlong/lo7ziovu/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 300, in _download_node
                repository_ctx.download_and_extract(<4 more arguments>)
java.io.IOException: Error downloading [https://nodejs.org/dist/v12.9.1/node-v12.9.1-win-x64.zip] to C:/users/chenjianlong/_bazel_chenjianlong/lo7ziovu/external/nodejs_windows_amd64/bin/nodejs/node-v12.9.1-win-x64.zip: connect timed out
Loading: 0 packages loaded
    Fetching @npm; Restarting. 55s
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn -s bazel query --output=label "attr('tags', '\[.*release-package.*\]', //src/...) intersect kind('.*_package', //src/...)"
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at exec (F:\front-end\angular-component\scripts\build-packages-dist.js:115:18)
    at buildReleasePackages (F:\front-end\angular-component\scripts\build-packages-dist.js:58:19)
    at defaultBuildReleasePackages (F:\front-end\angular-component\scripts\build-packages-dist.js:44:3)
    at Object.<anonymous> (F:\front-end\angular-component\scripts\build-packages-dist.js:36:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14) {
  status: 7,
  signal: null,
  output: [ null, <Buffer >, null ],
  pid: 5628,
  stdout: <Buffer >,
  stderr: null

**Comment by jelbourn** [comment]
This seems like an issue with your local environment; one or more of the binary downloads timed out during install. Unfortunately we can't provide much support in this area.
