### ISSUE TITLE
bug(cdk): Update Failed : Cannot read property 'length' of null

### ISSUE THREAD

**Issue by filol** [angular/components#19779]
#### Reproduction

I can't share my code because it's a big project, hope the stack will help you
`ng update @angular/material --force`
 
#### Expected Behavior

Working

#### Actual Behavior

```
 ** Executing migrations for package '@angular/cdk' **
Cannot read property 'length' of null
```
Stack trace in log file : 

```
[error] TypeError: Cannot read property 'length' of null
    at Object.computeLineStartsMap (path\node_modules\@angular\cdk\schematics\update-tool\utils\line-mappings.js:39:23)
    at ComponentResourceCollector.resolveExternalStylesheet (path\node_modules\@angular\cdk\schematics\update-tool\component-resource-collector.js:131:47)
    at path\node_modules\@angular\cdk\schematics\update-tool\index.js:97:50
    at Array.forEach (<anonymous>)
    at UpdateProject.migrate (path\node_modules\@angular\cdk\schematics\update-tool\index.js:95:35)
    at runMigrations (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:128:42)
    at Object.<anonymous> (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:83:17)
    at Generator.next (<anonymous>)
    at path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:11:12)
    at path\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:57:31
    at MergeMapSubscriber.project (path\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (path\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (path\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (path\node_modules\rxjs\internal\Subscriber.js:66:18)
```

#### Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.4.0
OS: win32 x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/flex-layout              10.0.0-beta.32
@ngtools/webpack                  10.0.0
@schematics/angular               9.1.9
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
```

- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by devversion** [comment]
@filol Thanks for this issue! Do you know if you have any files in your project that are not readable? or in better terms which might have permission issues? We have a fix for this in progress, but we'd like to understand how this issue surfaces on your end.

If possible, it would be great to have the requested information above, and potentially when you get a chance, it might be helpful if you manually modify the `resolveExternalStylesheet` function and log/debug the file path. That would be awesome.

If that's not possible (due to the incremental nature of ng update), let me know. Not a big deal. Thanks!

**Comment by filol** [comment]
@devversion @crisbeto I checked I have all the rights, I even closed my IDE, launched the console in administrator mode and it is exactly the same error.

I'm not sure I understood the "requested information above" of your message.

I have manually log the path, the error is throw on the first path :

```
Repository is not clean. Update changes will be mixed with pre-existing changes.
Using package manager: 'yarn'
Collecting installed dependencies...
Found 59 dependencies.
** Executing migrations of package '@angular/material' **

> Updates Angular Material to v10
Path : components/business/appels-d-offres/appels-d-offres.component.scss
× Migration failed: Cannot read property 'length' of null
  See "C:\Users\FRANOI~1\AppData\Local\Temp\ng-SlLOJo\angular-errors.log" for further details.

```

If you want i can provide you this file but it's really basic

**Comment by devversion** [comment]
@filol Thanks! yeah, with `information above` I actually just referred to the "permission issues". Thanks for checking that.

Does your project have the file `components/business/appels-d-offres/appels-d-offres.component.scss`? It would be interesting to see if the `components` folder is directly at same level with the `angular.json` file. Can you please check that? That would be all.

**Comment by filol** [comment]
@devversion Yes, he exist and no they are not on the same level. Here is the return of the tree command without the files not relevant

````
├──  .prettierignore
├── Dockerfile
├── README.md
├── angular.json
├── buildspec-pr.yml
├── buildspec-staging.yml
├── buildspec.yml
├── e2e
│   ├── protractor.conf.js
│   ├── src
│   │   ├── app.e2e-spec.ts
│   │   └── app.po.ts
│   └── tsconfig.json
├── git.version.ts
├── images
│   └── architecture.png
├── karma.conf.js
├── package-lock.json
├── package.json
├── scripts
├── src
│   ├── app
│   │   ├── app-routing.module.ts
│   │   ├── app.component.html
│   │   ├── app.component.scss
│   │   ├── app.component.ts
│   │   ├── app.module.ts
│   │   ├── components
│   │   │   ├── business
│   │   │   │   ├── appels-d-offres
│   │   │   │   │   ├── appels-d-offres-routing.module.ts
│   │   │   │   │   ├── appels-d-offres.component.html
│   │   │   │   │   ├── appels-d-offres.component.scss
│   │   │   │   │   ├── appels-d-offres.component.ts
│   │   │   │   │   └── appels-d-offres.module.ts
│   │   │   │   ├── business-routing.module.ts
│   │   │   │   ├── business.module.ts
│   │   ├── directives
│   │   ├── errors
│   │   ├── guards
│   │   ├── interceptors
│   │   ├── interfaces
│   │   ├── models
│   │   ├── pipes
│   │   ├── services
│   │   └── utils
│   ├── assets
│   ├── environments
│   │   ├── environment.prod.ts
│   │   ├── environment.staging.ts
│   │   ├── environment.ts
│   │   └── versions.ts
│   ├── favicon.ico
│   ├── index.html
│   ├── main.ts
│   ├── polyfills.ts
│   ├── styles
│   ├── styles.scss
│   └── test.ts
├── tree.txt
├── tsconfig.app.json
├── tsconfig.base.json
├── tsconfig.json
├── tsconfig.spec.json
├── tslint.json
```

**Comment by devversion** [comment]
Reopening this as the error has been fixed, but it doesn't _fix_ that actual stylesheets are not migrated. It looks like `ng update` has been run from within a different folder somehow. My understanding though was that the Angular CLI no longer supports this / that the devkit virtual tree always starts from the workspace root.
