### ISSUE TITLE
docs-bug(table): stackblitz example is not working

### ISSUE THREAD

**Issue by p770820** [angular/components#20271]
https://material.angular.io/components/table/overview

https://stackblitz.com/angular/ggbbllnexbk?file=src%2Fapp%2Ftable-basic-example.ts

![image](https://user-images.githubusercontent.com/9010279/89981967-6b88d480-dca7-11ea-99e3-97075645fd74.png)

**Comment by intellix** [comment]
I guess this explains why our unit tests started failing in 10.1.13:
```
SessionTableComponent › should create
    TypeError: Cannot read property 'nativeElement' of undefined
      at MatTable.CdkTable (../../../src/cdk/table/table.ts:442:24)
      at new MatTable (../../../src/material/table/table.ts:20:1)
      at NodeInjectorFactory.MatTable_Factory [as factory] (../../node_modules/@angular/material/bundles/material-table.umd.js:345:55)
```

**Comment by crisbeto** [comment]
This is odd since it doesn't happen locally in our dev app. I have a feeling that it might be the same issue as https://github.com/angular/components/issues/17075. Are you testing your code in es2015?

**Comment by p770820** [comment]
I use version 9.2.4 , it works.

https://v9.material.angular.io/components/table/overview
https://stackblitz.com/angular/jbnbdjvjame?file=src%2Fapp%2Ftable-basic-example.ts

![image](https://user-images.githubusercontent.com/9010279/90087531-9dee0c80-dd4f-11ea-8e9d-d83e9ce812ea.png)

https://v9.material.angular.io/components/table/overview

**Comment by devversion** [comment]
It looks like this is an issue in Angular. I've created: https://github.com/angular/angular/issues/38453
