### ISSUE TITLE
help(GoogleMap): TypeError: target.addListener is not a function

### ISSUE THREAD

**Issue by George35mk** [angular/components#21392]
#### What are you trying to do?

What are you trying to do?
I am trying to test a component that uses the angular material google maps

#### What troubleshooting steps have you tried?
I have try to create a Spy with jasmine but I can't change the value of MapEventManager.

What are you seeing that does not match your expectations? 

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: 
- Components: https://stackblitz.com/fork/components-issue 
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Create a component and use the `GoogleMapsModule.GoogleMap` component
2. Try to test this component, the test should be pass.
  
#### Environment

- Angular: 11
- CDK/Material: 11.0.1
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  W10 PRO

```
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.3
Node: 14.15.0
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.3 (cli-only)
@angular-devkit/build-angular      0.1100.3
@angular-devkit/core               11.0.3 (cli-only)
@angular-devkit/schematics         11.0.3
@angular/cdk                       11.0.1
@angular/flex-layout               11.0.0-beta.33
@angular/google-maps               11.0.1
@angular/material                  11.0.1
@angular/material-moment-adapter   11.0.1
@schematics/angular                11.0.3
@schematics/update                 0.1100.3
ng-packagr                         11.0.3
rxjs                               6.6.3
typescript                         4.0.5
```

### HeatMapComponent.html

```html
<google-map #gMap class="map"
    [width]="'100%'"
    [height]="'100%'"
    [center]="center"
    [zoom]="zoom"
    [options]="mapOptions"
    (centerChanged)="centerChangedSub.next($event)">
</google-map>
```

### HeatMapComponent.ts

```ts
import { AfterViewInit, Component, Input, OnDestroy, OnInit, ViewChild } from '@angular/core';
import type { GoogleMap } from '@angular/google-maps';

@Component({
  selector: 'mw-heat-map',
  templateUrl: './heat-map.component.html',
  styleUrls: ['./heat-map.component.scss']
})
export class HeatMapComponent implements OnInit, AfterViewInit, OnDestroy {
  /** The target map element */
  @ViewChild('gMap', { static: false }) gMap: GoogleMap; <---- the problem

  constructor( ) { }

  ngOnInit() {... }

  ngAfterViewInit() { ... }

  ngOnDestroy() { ... }

}

```

### heat-map.component.spec.ts

```ts
import { NO_ERRORS_SCHEMA } from '@angular/core';
import { waitForAsync, ComponentFixture, fakeAsync, TestBed, tick } from '@angular/core/testing';
import { GoogleMap, GoogleMapsModule } from '@angular/google-maps';
import { googleSpy } from '../GoogleSpy';
import { DEFAULT_STYLE } from '../map-styles/default-style';
import { HeatmapLocation, IHeatMapData } from '../map.interface';
import { HeatMapComponent } from './heat-map.component';

const MapEventManagerSpy = jasmine.createSpyObj(
  'MapEventManager',
  ['addListener', 'getLazyEmitter', 'setTarget', 'destroy', '_clearListeners'],
  ['_targetStream', '_listeners', '_pending']
);

const GoogleMapSpy = jasmine.createSpyObj(
  'GoogleMap',
  ['getCenter'],
  {
    data: jasmine.createSpy('data'),
    // _eventManager: MapEventManagerSpy, // not working
    _eventManager: jasmine.createSpy('_eventManager').and.returnValue({}) // not working
  }
);


fdescribe('HeatMapComponent', () => {
  let component: HeatMapComponent;
  let fixture: ComponentFixture<HeatMapComponent>;
  window.google = googleSpy;

  console.log({googleSpy});
  console.log({GoogleMapSpy});

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      imports: [ GoogleMapsModule ],
      declarations: [ HeatMapComponent ],
      providers: [
        { provide: GoogleMap, useValue: GoogleMapSpy}
      ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(HeatMapComponent);
    component = fixture.componentInstance;

    // component.gMap = TestBed.createComponent(GoogleMapSpy).componentInstance as GoogleMap;
    // component.gMap['_eventManager'] = MapEventManagerSpy;
    component.gMap = GoogleMapSpy;
    fixture.detectChanges();
    component.gMap = GoogleMapSpy;
    // component.mapOptions = GoogleMapSpy;

  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

});

```

```error
error properties: Object({ longStack: 'TypeError: target.addListener is not a function
    at Observable._subscribe (http://localhost:9877/_karma_webpack_/webpack:/src/google-maps/map-event-manager.ts:45:33)
    at Observable._trySubscribe (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Observable.ts:238:19)
    at Observable.subscribe (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Observable.ts:219:14)
    at innerSubscribe (http://localhost:9877/_karma_webpack_/webpack:/src/internal/innerSubscribe.ts:111:19)
    at SwitchMapSubscriber._innerSub (http://localhost:9877/_karma_webpack_/webpack:/src/internal/operators/switchMap.ts:137:44)
    at SwitchMapSubscriber._next (http://localhost:9877/_karma_webpack_/webpack:/src/internal/operators/switchMap.ts:126:10)
    at SwitchMapSubscriber.next (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Subscriber.ts:99:12)
    at BehaviorSubject.next (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Subject.ts:70: ...
TypeError: target.addListener is not a function
    at Observable._subscribe (http://localhost:9877/_karma_webpack_/webpack:/src/google-maps/map-event-manager.ts:45:33)
    at Observable._trySubscribe (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Observable.ts:238:19)
    at Observable.subscribe (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Observable.ts:219:14)
    at innerSubscribe (http://localhost:9877/_karma_webpack_/webpack:/src/internal/innerSubscribe.ts:111:19)
    at SwitchMapSubscriber._innerSub (http://localhost:9877/_karma_webpack_/webpack:/src/internal/operators/switchMap.ts:137:44)
    at SwitchMapSubscriber._next (http://localhost:9877/_karma_webpack_/webpack:/src/internal/operators/switchMap.ts:126:10)
    at SwitchMapSubscriber.next (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Subscriber.ts:99:12)
    at BehaviorSubject.next (http://localhost:9877/_karma_webpack_/webpack:/src/internal/Subject.ts:70:17)
    at BehaviorSubject.next (http://localhost:9877/_karma_webpack_/webpack:/src/internal/BehaviorSubject.ts:43:5)
    at MapEventManager.setTarget (http://localhost:9877/_karma_webpack_/webpack:/src/google-maps/map-event-manager.ts:70:24)
    at <Jasmine>
    at Object.onScheduleTask (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:117:26)
    at ZoneDelegate.scheduleTask (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:409:55)
    at Object.onScheduleTask (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:306:84)
    at ZoneDelegate.scheduleTask (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:409:55)
    at Zone.scheduleTask (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:243:47)
    at Zone.scheduleMacroTask (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:266:29)
    at scheduleMacroTaskWithCurrentZone (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:711:29)
    at http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:3095:32
```

### So I found the issue is with `MapEventManager` on this line

```ts
export class MapEventManager {
  /** Pending listeners that were added before the target was set. */
  private _pending: {observable: Observable<any>, observer: Subscriber<any>}[] = [];
  private _listeners: google.maps.MapsEventListener[] = [];
  private _targetStream = new BehaviorSubject<MapEventManagerTarget>(undefined);

  /** Clears all currently-registered event listeners. */
  private _clearListeners() {
    for (const listener of this._listeners) {
      listener.remove();
    }

    this._listeners = [];
  }

  constructor(private _ngZone: NgZone) {}

  /** Gets an observable that adds an event listener to the map when a consumer subscribes to it. */
  getLazyEmitter<T>(name: string): Observable<T> {
    return this._targetStream.pipe(switchMap(target => {
      const observable = new Observable<T>(observer => {
        // If the target hasn't been initialized yet, cache the observer so it can be added later.
        if (!target) {
          this._pending.push({observable, observer});
          return undefined;
        }

        const listener = target.addListener(name, (event: T) => { // <------------------- here i get the error
          this._ngZone.run(() => observer.next(event));
        });
        this._listeners.push(listener);
        return () => listener.remove();
      });

      return observable;
    }));
  }
```

I can't mock or spy on MapEventManager, I have try multiple solutions from the web and by my self but non of them are 
the solution in my problem. 

```ts
@ViewChild('gMap', { static: false }) gMap: GoogleMap;
``` 

Is not change
```ts
beforeEach(() => {
    fixture = TestBed.createComponent(HeatMapComponent);
    component = fixture.componentInstance;
    // component.gMap = TestBed.createComponent(GoogleMapSpy).componentInstance as GoogleMap;
    // component.gMap['_eventManager'] = MapEventManagerSpy;
    component.gMap = GoogleMapSpy;
    fixture.detectChanges();
    component.gMap = GoogleMapSpy;
    // component.mapOptions = GoogleMapSpy;

    console.log(component);
  });
```

**Comment by George35mk** [comment]
Can someone show me an example of a component test that uses the angular components google map?

**Comment by crisbeto** [comment]
Since you're stubbing out the `GoogleMap` object, you have to provide a stub for the `addListener` method as well. It seems like you're only stubbing `getCenter` at the moment. You can see how we're testing [the the map here](https://github.com/angular/components/blob/master/src/google-maps/google-map/google-map.spec.ts) and here's an example of [how we stub out the global objects](https://github.com/angular/components/blob/71b7b15958ee732fbe1398d68705143eb0e820e3/src/google-maps/testing/fake-google-map-utils.ts#L37).

**Comment by George35mk** [comment]
@crisbeto Thank you, your comment help me to solve the issue.
