### ISSUE TITLE
help(google-map): Angular universal can't call get google via jsonp call  

### ISSUE THREAD

**Issue by kimbbra** [angular/components#22059]
I am trying to run the simple angular app (universal) with the google map component.  After calling the `serve:ssr` application compiled successfully,  I get 
```
Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
```
When I open  `http://localhost:4200` for a few second see a blank page, and the got error in console.
```
    at ApplyRedirects.noMatchError (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212605:16)
    at CatchSubscriber.selector (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212587:28)
    at CatchSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:87969:31)
    at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
    at MapSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
    at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
    at MapSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
    at ThrowIfEmptySubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
    at ThrowIfEmptySubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
    at TakeLastSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
    at resolvePromise (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121787:39)
    at resolvePromise (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121739:21)
    at /Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121849:21
    at ZoneDelegate.crGB.ZoneDelegate.invokeTask (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121376:35)
    at Object.onInvokeTask (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:159898:33)
    at ZoneDelegate.crGB.ZoneDelegate.invokeTask (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121375:40)
    at Zone.crGB.Zone.runTask (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121143:51)
    at drainMicroTaskQueue (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121556:39)
    at crGB.ZoneTask.invokeTask (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121462:25)
    at Server.ZoneTask.invoke (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:121447:52) {
  rejection: Error: Cannot match any routes. URL Segment: 'sockjs-node/info'
      at ApplyRedirects.noMatchError (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212605:16)
      at CatchSubscriber.selector (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212587:28)
      at CatchSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:87969:31)
      at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
      at MapSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
      at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
      at MapSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
      at ThrowIfEmptySubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
      at ThrowIfEmptySubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
      at TakeLastSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'sockjs-node/info'
        at ApplyRedirects.noMatchError (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212605:16)
        at CatchSubscriber.selector (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212587:28)
        at CatchSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:87969:31)
        at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
        at MapSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
        at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
        at MapSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
        at ThrowIfEmptySubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
        at ThrowIfEmptySubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
        at TakeLastSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
  },
  zone: <ref *1> Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: <ref *2> ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular *1],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular *1],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular *1],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular *1],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular *1],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular *1],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular *2],
      _hasTaskCurrZone: [Circular *1]
    }
  },
  task: ZoneTask {
    _zone: <ref *1> Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: Error: Cannot match any routes. URL Segment: 'sockjs-node/info'
          at ApplyRedirects.noMatchError (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212605:16)
          at CatchSubscriber.selector (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:212587:28)
          at CatchSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:87969:31)
          at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
          at MapSubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
          at MapSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
          at MapSubscriber.error (/U
sers/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
          at ThrowIfEmptySubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
          at ThrowIfEmptySubscriber.error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73343:18)
          at TakeLastSubscriber._error (/Users/kimbra/WebstormProjects/work/kotokit-fe/dist/kotokit-fe/server/main.js:73363:26)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function (anonymous)],
    invoke: [Function (anonymous)]
  }
}
```

After some research, I understand that if I remove the request to google maps API, the app will load.

```
 loadMap(): Observable<boolean> {
    return this.http
      .jsonp('https://maps.googleapis.com/maps/api/js?key=${key}', 'callback')
      .pipe(
        map(() => true),
        take(1),
        catchError(() => of(false))
      );
```

How I can load this API key and make google map work with universal?

```
//server.ts

import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';
const request = require('request');

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/kotokit-fe/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule,
    })
  );

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get(
    '*.*',
    express.static(distFolder, {
      maxAge: '1y',
    })
  );

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run(): void {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = (mainModule && mainModule.filename) || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
```

```
//package.json
 
 "dependencies": {
    "@angular/animations": "~11.1.0",
    "@angular/cdk": "^11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/google-maps": "11.1.0",
    "@angular/material": "^11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/platform-server": "~11.1.0",
    "@angular/router": "~11.1.0",
    "@ngneat/until-destroy": "^8.0.3",
    "@nguniversal/express-engine": "^11.1.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@types/googlemaps": "3.43.2",
    "express": "^4.15.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.1",
    "@angular/cli": "~11.1.1",
    "@angular/compiler-cli": "~11.1.0",
    "@nguniversal/builders": "^11.1.2",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "git-format-staged": "^2.1.0",
    "husky": "^4.3.6",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "lint-staged": "^10.5.3",
    "prettier": "^2.2.1",
    "pretty-quick": "^3.1.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  }
  ```

**Comment by crisbeto** [comment]
The `google-map` and related components aren't meant to be used on the server since Google Maps depends on a lot of browser-specific APIs. Even if you did manage to download the script, I doubt that it would run and [we have some checks](https://github.com/angular/components/blob/master/src/google-maps/google-map/google-map.ts#L235) that turn the component into a no-op if it isn't inside of a browser.
