### ISSUE TITLE
bug: Sanity checks run in test environement

### ISSUE THREAD

**Issue by eweap** [angular/components#23365]
As I explained in comment on PR ( https://github.com/angular/components/pull/23289 ) I have a lot of warnings coming from angular material sanity checks during my unit test runs, what makes the output unreadable.
@jelbourn advised me to open an issue because sanity checks should not run in test environment.

Thanks for your help !

Steps to reproduce:
1. Fork https://github.com/eweap/angular-material-warn
2. Run `yarn install` then run test with `yarn nx test ui` to run the test for the ui lib (its a nrwl/nx workspace)
 
 
#### Expected Behavior

What behavior were you expecting to see?
No warning should be display during the test run

#### Actual Behavior

What behavior did you actually see?
A warning is displayed:

```
console.warn
      Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

      at MatCommonModule.Object.<anonymous>.MatCommonModule._checkThemeIsPresent (../../../src/material/core/common-behaviors/common-module.ts:144:15)
      at new MatCommonModule (../../../src/material/core/common-behaviors/common-module.ts:81:12)
      at Object.MatCommonModule_Factory [as factory] (../../node_modules/@angular/material/bundles/material-core.umd.js:189:69)
      at R3Injector.Object.<anonymous>.R3Injector.hydrate (../../../packages/core/src/di/r3_injector.ts:416:29)
      at R3Injector.Object.<anonymous>.R3Injector.get (../../../packages/core/src/di/r3_injector.ts:211:23)
      at ../../../packages/core/src/di/r3_injector.ts:247:51
          at Set.forEach (<anonymous>)
      at R3Injector.Object.<anonymous>.R3Injector._resolveInjectorDefTypes (../../../packages/core/src/di/r3_injector.ts:247:27)
```

#### Environment

- Angular: 12.2.1
- CDK/Material: 12.2.1
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by jelbourn** [comment]
@crisbeto it looks like we should update our test env check to look for jest

**Comment by michaelfaith** [comment]
Glad this is being addressed.  Just hit this myself, when updating to the latest.  Thanks for the quick turnaround.

**Comment by kpaxton** [comment]
Running into this as well after the latest update.

**Comment by crisbeto** [comment]
@eweap which test runner are you seeing the problem on?

**Comment by eweap** [comment]
@crisbeto In my reproduction example I use Jest 27.0.3

**Comment by crisbeto** [comment]
Hmm, I suspect that the fix didn't work for Jest, because we're checking for the presence of `window.jest`, but we need to do something like `typeof jest !== 'undefined'` instead since it doesn't run inside a browser.

**Comment by kpaxton** [comment]
@crisbeto You are correct. I just tested this by modifying the bundled output from cdk-platform.umd.js
```
return (typeof testGlobals.__karma__ !== 'undefined' && !!testGlobals.__karma__) ||
            (typeof testGlobals.jasmine !== 'undefined' && !!testGlobals.jasmine) ||
            (typeof jest !== 'undefined' && !!jest) ||
            (typeof testGlobals.Mocha !== 'undefined' && !!testGlobals.Mocha);
```
This works.

I initially output the contents of `testGlobals.jest` and just `jest` to confirm.
```
console.warn('***************************TEST ENVIRONMENT*********************************', testGlobals.jest, jest);
output:
console.warn
    ***************************TEST ENVIRONMENT********************************* undefined {
      advanceTimersByTime: [Function: advanceTimersByTime],
      advanceTimersToNextTimer: [Function: advanceTimersToNextTimer],
      autoMockOff: [Function: disableAutomock],
      autoMockOn: [Function: enableAutomock],
      clearAllMocks: [Function: clearAllMocks],
      clearAllTimers: [Function: clearAllTimers],
      createMockFromModule: [Function: createMockFromModule],
      deepUnmock: [Function: deepUnmock],
      disableAutomock: [Function: disableAutomock],
      doMock: [Function: mock],
      dontMock: [Function: unmock],
      enableAutomock: [Function: enableAutomock],
      fn: [Function: bound fn],
      genMockFromModule: [Function: genMockFromModule],
      getRealSystemTime: [Function: getRealSystemTime],
      getTimerCount: [Function: getTimerCount],
      isMockFunction: [Function: isMockFunction],
      isolateModules: [Function: isolateModules],
      mock: [Function: mock],
      requireActual: [Function: bound requireActual],
      requireMock: [Function: bound requireMock],
      resetAllMocks: [Function: resetAllMocks],
      resetModules: [Function: resetModules],
      restoreAllMocks: [Function: restoreAllMocks],
      retryTimes: [Function: retryTimes],
      runAllImmediates: [Function: runAllImmediates],
      runAllTicks: [Function: runAllTicks],
      runAllTimers: [Function: runAllTimers],
      runOnlyPendingTimers: [Function: runOnlyPendingTimers],
      setMock: [Function: setMock],
      setSystemTime: [Function: setSystemTime],
      setTimeout: [Function: setTimeout],
      spyOn: [Function: bound spyOn],
      unmock: [Function: unmock],
      unstable_mockModule: [Function: mockModule],
      useFakeTimers: [Function: useFakeTimers],
      useRealTimers: [Function: useRealTimers]
    }
```

**Comment by crisbeto** [comment]
Great, thank you for testing! I'll submit a fix for it later today.

**Comment by michaelfaith** [comment]
> Hmm, the changes are based on this [#23365 (comment)](https://github.com/angular/components/issues/23365#issuecomment-926619093). Can you double-check your `node_modules` that you actually received the changes?

@crisbeto  This is what that part of `cdk-platform.umd.js` looks like for me, which appears to have the code update, but still gives the warnings.  
```
/** Gets whether the code is currently running in a test environment. */
    function _isTestEnvironment() {
        return (typeof testGlobals.__karma__ !== 'undefined' && !!testGlobals.__karma__) ||
            (typeof testGlobals.jasmine !== 'undefined' && !!testGlobals.jasmine) ||
            (typeof testGlobals.jest !== 'undefined' && !!testGlobals.jest) ||
            (typeof testGlobals.Mocha !== 'undefined' && !!testGlobals.Mocha);
    }
```

If I change that to match what @kpaxton had with just `jest` without testGlobals, then the warnings don't show. 
```
function _isTestEnvironment() {
        return (typeof testGlobals.__karma__ !== 'undefined' && !!testGlobals.__karma__) ||
            (typeof testGlobals.jasmine !== 'undefined' && !!testGlobals.jasmine) ||
            (typeof jest !== 'undefined' && !!jest) ||                                  // <--- This
            (typeof testGlobals.Mocha !== 'undefined' && !!testGlobals.Mocha);
    }
```

**Comment by michaelfaith** [comment]
Well dang, this one's proven to be a real bugger. I guess it would be appropriate to re-open the issue?

**Comment by crisbeto** [comment]
Yeah, good point, that could work. Another option I was thinking of was to refer to `jest` directly like you mentioned above, but then `// @ts-ignore` the error instead of using a `declare const` in order to keep both TS and Closure happy.

**Comment by michaelfaith** [comment]
*fingers crossed this makes it into 13*  (also, hurrah for 13 🎉)
