### ISSUE TITLE
bug(update schematic): Updating from v11 to v12 fails with Typescript 4.4.*

### ISSUE THREAD

**Issue by LucaVazz** [angular/components#23644]
#### Reproduction

In a halfway updated app (i.e. Angular updated to version 12 while Angular Material is still at 11), try to run an update to Angular Material 11 via the Angular CLI when Typescript **4.4** is installed in the project.

Steps to reproduce:
1.  `npx @angular/cli@11 new`
2. go into newly created app directory
3. `npx @angular/cli@11 add @angular/material@11`
4. `ng update @angular/core@12 @angular/cli@12`
5. replace typescript version in package.json with `^4.4.0`
6. `npm i`
7. `npx @angular/cli@12 update @angular/material`
 
 
#### Expected Behavior

Update of Angular Material works with all migrations.

#### Actual Behavior

Update of Angular Material aborts with the following output:
```
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cdk @ "12.2.7" (was "11.2.13")...
    Updating package.json with dependency @angular/material @ "12.2.7" (was "11.2.13")...
  UPDATE package.json (1262 bytes)
√ Packages successfully installed.
** Executing migrations of package '@angular/cdk' **

> Updates the Angular CDK to v12.
× Migration failed: directoryExists is not a function
  See "C:\Users\LucaV\AppData\Local\Temp\ng-nBUvvO\angular-errors.log" for further details.
```
```
 cat C:\Users\LucaV\AppData\Local\Temp\ng-nBUvvO\angular-errors.log
[error] TypeError: directoryExists is not a function
    at Object.matchFiles (D:\ng11to12\node_modules\typescript\lib\typescript.js:20102:17)
    at FileSystemHost.readDirectory (D:\ng11to12\node_modules\@angular\cdk\schematics\update-tool\utils\virtual-host.js:45:19)
    at getFileNamesFromConfigSpecs (D:\ng11to12\node_modules\typescript\lib\typescript.js:40747:40)
    at getFileNames (D:\ng11to12\node_modules\typescript\lib\typescript.js:40250:29)
    at parseJsonConfigFileContentWorker (D:\ng11to12\node_modules\typescript\lib\typescript.js:40183:24)
    at Object.parseJsonConfigFileContent (D:\ng11to12\node_modules\typescript\lib\typescript.js:40124:16)
    at Object.parseTsconfigFile (D:\ng11to12\node_modules\@angular\cdk\schematics\update-tool\utils\parse-tsconfig.js:22:15)
    at Function.createProgramFromTsconfig (D:\ng11to12\node_modules\@angular\cdk\schematics\update-tool\index.js:158:41)
    at runMigrations (D:\ng11to12\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:119:57)
    at Object.<anonymous> (D:\ng11to12\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:91:17)
```

#### Environment

- Angular: 12
- CDK/Material: 11, trying to update to 12
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Node LTS

#### Work around

Lock the Typescript version in the package.json as `~4.2.4`, run `npm i` and than run the update command for Angular Material.

#### Possible cause

Typescript 4.4 seems to have changed the API for `matchFiles`, see e.g. https://github.com/parcel-bundler/parcel/issues/6779 for more details.

**Comment by crisbeto** [comment]
TypeScript 4.4 support hasn't been officially released yet. We merge in the changes to the framework last week and we'll update this repo soon.

**Comment by crisbeto** [comment]
Will be resolved by https://github.com/angular/components/pull/23646.
