### ISSUE TITLE
bug(material): platform._isTestEnvironment

### ISSUE THREAD

**Issue by eng-dibo** [angular/components#23914]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when I run my universal Angular app I got `platform._isTestEnvironment is not a function`
my `@angular/material` version matches `@ancular/cdk` as [mentioned here](https://github.com/angular/components/issues/23690#issuecomment-934543587)

**ng version:**
```
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.6
@angular-devkit/build-angular   12.2.6
@angular-devkit/core            12.2.6
@angular-devkit/schematics      12.2.13
@angular/cdk                    12.2.1
@angular/cli                    12.2.13
@angular/material               12.2.1
@nguniversal/express-engine     12.1.0
@schematics/angular             12.2.13
rxjs                            6.6.7
typescript                      4.3.5
```
 
this error occurs when I run `node server/main` in Docker.
the same app in my local machine works (the same environment and node version).
I create the docker container from the output 'dist'

**error trace:**
```
the server is working in production mode
(node:10) Warning: Accessing non-existent property 'prod' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Node Express server is listening on http://localhost:4200
TypeError: platform._isTestEnvironment is not a function
    at MatCommonModule._checkIsEnabled (/ngx-cms/node_modules/@angular/material/bundles/material-core.umd.js:136:45)
    at MatCommonModule._checkDoctypeIsDefined (/ngx-cms/node_modules/@angular/material/bundles/material-core.umd.js:145:22)
    at new MatCommonModule (/ngx-cms/node_modules/@angular/material/bundles/material-core.umd.js:124:22)
    at Object.MatCommonModule_Factory [as factory] (/ngx-cms/node_modules/@angular/material/bundles/material-core.umd.js:179:69)
    at R3Injector.hydrate (/ngx-cms/node_modules/@angular/core/bundles/core.umd.js:11960:39)
    at R3Injector.get (/ngx-cms/node_modules/@angular/core/bundles/core.umd.js:11774:37)
    at /ngx-cms/node_modules/@angular/core/bundles/core.umd.js:11813:77
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (/ngx-cms/node_modules/@angular/core/bundles/core.umd.js:11813:35)
    at new NgModuleRef$1 (/ngx-cms/node_modules/@angular/core/bundles/core.umd.js:26022:31)
```

### Reproduction

.

### Expected Behavior

work normally

### Actual Behavior

error: `platform._isTestEnvironment is not a function`

### Environment

- Angular: 12.2.13
- CDK/Material:  12.2.1
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): Linux

** note:**
solved by changing all `@angular/*` versions to `^12.2.1` not only material and cdk. but don't know why

**Comment by crisbeto** [comment]
My guess is that you ended up with mismatching versions, even though the ones in the `package.json` were the same. npm probably aligned them automatically when you bumped the version of the framework.
