### ISSUE TITLE
bug(MatDialog): js error on open in combination with ngx-translate TranslateService

### ISSUE THREAD

**Issue by lujakob** [angular/components#24317]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Providing the TranslateService of ngx-translate/core in a component that is being opened with MatDialog.open causes a console javascript error. Even though the ngx-translate module and MatMaterialModule are being imported in the app.module there are two errors. 

First error:
NullInjectorError: No provider for TranslateService!

Second error: 
ERROR TypeError: Cannot read properties of undefined (reading 'focusInitialElementWhenReady')
    at MatDialogContainer._trapFocus

### Reproduction

Steps to reproduce:
1. Create a new minimal application with `ng new dialog-translate-test`
2. Install @angular/material @angular/cdk @ngx-translate/core
3. Create a TestDialogComponent and inject the TranslateService in the constructor.
4. Add a button element in the app.component.html that calls a component method to open the dialog
5. `this.dialog.open(TestDialogComponent)`

### Expected Behavior

The dialog is opened and no console error is thrown.

### Actual Behavior

core.mjs:6461 ERROR NullInjectorError: R3InjectorError(AppModule)[TranslateService -> TranslateService -> TranslateService]: 
  NullInjectorError: No provider for TranslateService!
    at NullInjector.get (core.mjs:11095:1)
    at R3Injector.get (core.mjs:11262:1)
    at R3Injector.get (core.mjs:11262:1)
    at R3Injector.get (core.mjs:11262:1)
    at NgModuleRef.get (core.mjs:21807:1)
    at Object.get (core.mjs:21484:1)
    at lookupTokenUsingModuleInjector (core.mjs:3334:1)
    at getOrCreateInjectable (core.mjs:3446:1)
    at Module.ɵɵdirectiveInject (core.mjs:14381:1)
    at NodeInjectorFactory.TestDialogComponent_Factory [as factory] (test-dialog.component.ts:9:33)
defaultErrorLogger @ core.mjs:6461
handleError @ core.mjs:6508
handleError @ core.mjs:10932
executeListenerWithErrorHandling @ core.mjs:14955
wrapListenerIn_markDirtyAndPreventDefault @ core.mjs:14990
(anonymous) @ platform-browser.mjs:465
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:25444
invokeTask @ zone.js:405
runTask @ zone.js:178
invokeTask @ zone.js:487
invokeTask @ zone.js:1600
globalZoneAwareCallback @ zone.js:1626
core.mjs:6461 ERROR TypeError: Cannot read properties of undefined (reading 'focusInitialElementWhenReady')
    at MatDialogContainer._trapFocus (dialog.mjs:233:33)
    at MatDialogContainer._onAnimationDone (dialog.mjs:332:18)
    at MatDialogContainer_animation_dialogContainer_done_HostBindingHandler (dialog.mjs:358:105)
    at executeListenerWithErrorHandling (core.mjs:14952:1)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:14990:1)
    at animations.mjs:189:34
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25457:1)
    at ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment]
By default the dialog is going to use the module-level injector so maybe you just haven't imported the translation module at the correct place? Alternatively, you can try to pass in a `viewContainerRef` when opening the dialog which will put it in the same injector tree as the component opening it. E.g. something like


```
class DialogOpener {
  constructor(private viewContainerRef: ViewContainerRef, private dialog: MatDialog) {}

  openDialog() {
    this.dialog.open(TestDialog, {viewContainerRef: this.viewContainerRef});
  }
}
```
