### ISSUE TITLE
bug(mat-selection-list): Configurable multiple input is not working

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#24946]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a mat-selection-list which has a input property multiple. 
I am trying to make the same input property configurable but it is not working.

### Reproduction

Steps to reproduce:
1. Open https://stackblitz.com/edit/angular-smq4le?file=src/app/list-single-selection-example.html
2. Just check/uncheck Toggle multiple checkbox and see mat-selection-list is not re-rendering to show single/multiple selection

### Expected Behavior

Configurable multiple input should work

### Actual Behavior

Configurable multiple input is not working

Error

```
ERROR Error: Cannot change `multiple` mode of mat-selection-list after initialization.
    at MatSelectionList.set multiple [as multiple] (vendor.js:119164:15)
    at Object.ngOnChangesSetInput [as setInput] (vendor.js:52637:25)
    at setInputsForProperty (vendor.js:63880:11)
    at elementPropertyInternal (vendor.js:62743:5)
    at Module.ɵɵproperty (vendor.js:67814:5)
    at ListSingleSelectionExample_Template (main.js:113:65)
    at executeTemplate (vendor.js:62297:5)
    at refreshView (vendor.js:62106:7)
    at refreshComponent (vendor.js:63509:7)
    at refreshChildComponents (vendor.js:61853:5)
```

### Environment

Available in stackblitz demo

**Comment by volvachev** [comment]
Hi, I think everything is working as expected. I'm looking at the comment code, `multiple` should not change at runtime, if it does, it gives an error.

**Comment by crisbeto** [comment]
This is working as expected. The error is there, because changing `multiple` is also going to change the value of the form control and we can't make an assumption of what the value will look like. E.g. if the control had an array value in single selection mode, would it stay an array in multi-selection mode or would be part of a 2D array?
