### ISSUE TITLE
bug(Dialog): Explicit injector does not work

### ISSUE THREAD

**Issue by adzhiljano** [angular/components#25262]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hey, I recently updated to v14 just for the newly added feature of the Dialog - the explicit injector, but it does not seem to work. I might be doing something wrong or misunderstood the new feature (to provide an `Injector` without having to provide a `ViewContainerRef`). 

### Reproduction

Steps to reproduce:
Check out https://stackblitz.com/edit/angular-ozdqwy?file=src%2Fapp%2Fdialog-overview-example.ts (hope this lives long enough) 
**OR**
1. Open the dialog example https://stackblitz.com/run?file=src/app/dialog-overview-example.ts
2. Add some service `@Injectable()
export class SomeService {
  test = 123;
}`
3. Create an injector `const myInjector = Injector.create({
      providers: [{ provide: SomeService }]
    });`
4. Pass the injector `injector: myInjector`` to ``this.dialog.open`
5. Require the service `public someService: SomeService` in `DialogOverviewExampleDialog`'s constructor

### Expected Behavior

`SomeService` gets provided to `DialogOverviewExampleDialog`

### Actual Behavior

```
ERROR NullInjectorError: R3InjectorError(AppModule)[SomeService -> SomeService -> SomeService]: 
  NullInjectorError: No provider for SomeService!
    at NullInjector.get (vendor.js:66456:21)
    at R3Injector.get (vendor.js:66652:27)
    at R3Injector.get (vendor.js:66652:27)
    at R3Injector.get (vendor.js:66652:27)
    at NgModuleRef.get (vendor.js:81766:29)
    at ChainedInjector.get (vendor.js:81534:32)
    at lookupTokenUsingModuleInjector (vendor.js:59680:31)
    at getOrCreateInjectable (vendor.js:59732:10)
    at Module.ɵɵdirectiveInject (vendor.js:67961:10)
    at NodeInjectorFactory.DialogOverviewExampleDialog_Factory [as factory] (main.js:153:195)
```

### Environment

Angular CLI: 14.0.5
Angular: 14.0.5
Angular Material: 14.0.4        
Node: 16.13.0
Package Manager: npm 8.1.0 
OS: win32 x64

### Additional info
I glanced into the source code and I think the injector from the config is taken into account only when creating/attaching the 
container:
https://github.com/angular/components/blob/c28bbdeb51c31cbd1f5e06528ef4d21b1650e4a8/src/cdk/dialog/dialog.ts#L224
but not when creating/attaching the actual content component:
https://github.com/angular/components/blob/c28bbdeb51c31cbd1f5e06528ef4d21b1650e4a8/src/cdk/dialog/dialog.ts#L311
and it seems that from a DI point of view, the implementation does not tie the content's Injector with the container's Injector. Again, I might be wrong.

Thanks!

**Comment by BenjaminHutchinson** [comment]
We have experienced the same, I've ended up needing to build components that (in a minor way) duplicate logic in order to specify providers instead of being able to pass up an injector.

**Comment by mpo-dev** [comment]
I have the same issue, the `MatDialog` implementation seems to work fine though, but the CDK dialog is unable to resolve the custom dependencies.

**Comment by adzhiljano** [comment]
Hey @mpo-dev , that is wierd. The example I posted in the Reproduction section uses the `MatDialog` . AFAIR `MatDialog` is just a thin wrapper around the cdk's `Dialog` and this issue should concern both of them.

**Comment by mpo-dev** [comment]
@adzhiljano In my production code I had the situation where opening a custom component in a dialog with `MatDialog` would work fine, but opening the same component in a dialog with `Dialog` would result in one of the custom components dependencies not being resolvable. I need the CDK `Dialog` because of the custom dialog container.

**Comment by yharaskrik** [comment]
I am also receiving this error using MatDialog on Angular 15.2.5

**Comment by adventmedia** [comment]
I am experiencing a similar NullInjector error for MatSelect:
```
ERROR NullInjectorError: R3InjectorError(AppModule)[MatLegacySelect -> MatLegacySelect -> MatLegacySelect]: 
  NullInjectorError: No provider for MatLegacySelect!
    at NullInjector.get (core.mjs:7493:27)
    at R3Injector.get (core.mjs:7914:33)
    at R3Injector.get (core.mjs:7914:33)
    at R3Injector.get (core.mjs:7914:33)
    at ChainedInjector.get (core.mjs:12084:36)
    at lookupTokenUsingModuleInjector (core.mjs:3201:39)
    at getOrCreateInjectable (core.mjs:3246:12)
    at Module.ɵɵdirectiveInject (core.mjs:10041:12)
    at NodeInjectorFactory.MatSelectSearchComponent_Factory [as factory] (ngx-mat-select-search.mjs:37:115)
    at getNodeInjectable (core.mjs:3431:44)
```

**Comment by VeselyT** [comment]
We are experiencing the same issue. Instead of providing only injector we are forced to provide also deprecated component factory resolver to instantiate it in the correct dependency injection context 

```
 this.matDialog.open(DialogComp, {
    injector: this.cmpInjector,
    componentFactoryResolver: this.cmpInjector.get(ComponentFactoryResolver),
  })
```

**Comment by tonyholt** [comment]
@VeselyT's solution worked for me.  I am trying to utilize a service to handle dialogs.  Passing the "viewContainerRef" argument wasn't working, but once I used the componentFactoryResolver like VesleyT, it worked.  The viewContainerRef option (or the injector option), are not passing the dependencies properly, as noted by others on this issue.

**Comment by rojasjandro89** [comment]
Having the same issue. I think the problem is in the ComponentPortal. I'm generating the dialog myself using portals and I'm experiencing the exact same behavior described by others.

Angular Version 17.2.3

**Comment by mironante** [comment]
> We are experiencing the same issue. Instead of providing only injector we are forced to provide also deprecated component factory resolver to instantiate it in the correct dependency injection context
> 
> ```
>  this.matDialog.open(DialogComp, {
>     injector: this.cmpInjector,
>     componentFactoryResolver: this.cmpInjector.get(ComponentFactoryResolver),
>   })
> ```

Thank you! Very helpful!

**Comment by Abreuvoir** [comment]
I'd like to bump this issue, it has caused problems for us with CDK Dialog, Angular & CDK version 18.2, where lazy modules opening dialogs from a providedIn root dialog service did not have access to their lazy services, despite passing their injector.
For now the workaround by passing to cdkDialog.open the deprecated ComponentFactoryResolver related to the injector works, but who knows for how long?
```
injector,
componentFactoryResolver: injector?.get(ComponentFactoryResolver),
```

**Comment by gguy0406** [comment]
The workaround using ComponentFactoryResolver does not work anymore in version 19. However, passing viewContainer to dialog config is working now.

**Comment by pavel-suk** [comment]
> The workaround using ComponentFactoryResolver does not work anymore in version 19. However, passing viewContainer to dialog config is working now.

Yep, i can confirm as well that its working

**Comment by yurakis** [comment]
I started facing this issue after upgrade to ng19. Surprisingly enough, it was working just fine without adding deprecated `ComponentFactoryResolver`. However, replacing injector with viewContainerRef resolved the issue.

**Comment by sy-filis** [comment]
I have the same problem after changing to standalone API in ng 19.

**Comment by crisbeto** [comment]
I suspect this was fixed in #30610.
