### ISSUE TITLE
bug(MatFormField): Prerendering Angular universal fails

### ISSUE THREAD

**Issue by Tom4U** [angular/components#25889]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If running `npm run prerender` and a component template, considered for prerendering, contains a MatFormField component, the prerendering fails:

```
⠋ Prerendering 6 route(s) to <DRIVE_LETTER>:\<project>\dist\<project>\browser...Unhandled Promise rejection: Cannot read properties of undefined (reading 'type') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'type')
    at TokenStream.LA (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:626334)
    at TokenStream.advance (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:624983)
    at Parser._readDeclarations (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:659046)
    at Parser.parseStyleAttribute (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:660636)
    at parseStyles (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:344961)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:345316)
    at CSSStyleDeclaration.value (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:346137)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:359933)
    at cloakElement (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558188)
    at <DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558406 TypeError: Cannot read properties of undefined (reading 'type')      
    at TokenStream.LA (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:626334)
    at TokenStream.advance (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:624983)
    at Parser._readDeclarations (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:659046)
    at Parser.parseStyleAttribute (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:660636)
    at parseStyles (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:344961)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:345316)
    at CSSStyleDeclaration.value (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:346137)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:359933)
    at cloakElement (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558188)
    at <DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558406
✖ Prerendering routes to <DRIVE_LETTER>:\<project>\dist\<project>\browser failed.
Cannot read properties of undefined (reading 'type')
```

### Reproduction

Steps to reproduce:
1. install **nguniversal/express-engine**
2. import **MatFormFieldModule** and **MatInputModule**
3. add code to a component template:
   ```html
   <form class="form">
        <mat-form-field appearance="fill">
            <input matInput>                
        </mat-form-field>
    </form>
   ```
4. run `npm run prerender`

### Expected Behavior

Prerendering should not fail.

### Actual Behavior

Prerendering fails.

### Environment

```
@angular-devkit/architect       0.1402.7
@angular-devkit/build-angular   14.2.7
@angular-devkit/core            14.2.7
@angular-devkit/schematics      14.2.7
@angular/cdk                    14.2.6
@angular/cli                    14.2.7
@angular/fire                   7.4.1
@angular/material               14.2.6
@nguniversal/builders           14.2.0
@nguniversal/express-engine     14.2.0
@schematics/angular             14.2.7
ng-packagr                      14.2.2
rxjs                            7.5.7
typescript                      4.7.4
```
- Browser(s): not relevant
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
Can you post an example that reproduces the issue? As far as I can tell from the stack trace, this error isn't coming from Angular Material. It's also worth noting that we have some server-side rendering tests that didn't pick this up.

**Comment by Tom4U** [comment]
It is somehow, because only if using <mat-form-field> it fails.

However. I tried to set up a new project and going forward step by step. As this didn't lead to anything, I've tried another approach and used my original project while step-by-step simplifying it.

And now I know what is not working in combination.

In my `AppComponent` I'm using the following HostBinding: `@HostBinding('style.--vh') vh = '1vh';`
If that is used combined with the MatFormField component, prerendering fails.

I've published my steps from the forward approach to GitHub (see single commits): [tom4u/debug-prerender-mat-form-field](https://github.com/Tom4U/debug-prerender-mat-form-field)

**Comment by crisbeto** [comment]
Thanks for the reproduction, it helped narrow down the issue. I spent some time investigating it, and it looks like this is a problem with the `domino` renderer that Angular uses for server-side DOM implementation. Domino doesn't support CSS variables and some CSS properties like `clip-path`, e.g. if you try doing `element.style.setProperty('--foo', '1px')`, the value just gets dropped. We work around it by writing directly to the `style` attribute instead: https://github.com/angular/angular/blob/main/packages/platform-server/src/server_renderer.ts#L298

The error in this specific case happens, because when the `--vh` variable is set, the element looks like `<app-root style="--vh:1vh"></app-root>`, but later on the Angular animations module tries to set `el.style.display = 'none'` on the same element. This tells Domino to parse the `style` attribute and it leads to the error, because Domino doesn't know how to deal with a property starting with `--`. It happens in the specific combination of the Material form field + CSS variables, because Material uses the Angular animations module to animate the error/hint messages, but it can also be reproduced with the following unit test:

```ts
it('fails', fakeAsync(() => {
  @Component({template: 'hello', selector: 'app-root'})
  class AppRoot {
    @HostBinding('style.--height') height = '100px';
  }

  @Component({
    template: '<app-root [@test]="animationState"></app-root>',
    animations: [trigger(
        'test',
        [
          state('enter', style({opacity: 1})),
          transition('void => enter', [style({opacity: 0}), animate('300ms linear')]),
        ])],
  })
  class MyApp {
    animationState = 'enter';
  }

  TestBed.configureTestingModule({declarations: [MyApp, AppRoot]});
  const fixture = TestBed.createComponent(MyApp);
  fixture.detectChanges();
  flush();
}));
```

The only workaround I've found, that doesn't involve an upstream fix in Domino, has been to ensure that at least one non-variable property is written to the DOM before any CSS variables. E.g. in your case you can work around it by adding a dummy host binding like `@HostBinding('style.color') color = 'inherit'` before the `@HostBinding('style.--vh')`. This workaround can be baked into Angular's server renderer as well, but it feels a little hacky.

I'm transferring the issue to the appropriate repo to continue the discussion.
