### ISSUE TITLE
bug(update cdk schematic to v15)

### ISSUE THREAD

**Issue by RobinKamps** [angular/components#26030]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

could not `ng update @angular/material@15`.
schematic for updating cdk fails:

```
ng update @angular/material@15
Using package manager: npm
Collecting installed dependencies...
Found 132 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cdk @ "15.0.0" (was "14.2.7")...
    Updating package.json with dependency @angular/material @ "15.0.0" (was "14.2.7")...
    Updating package.json with dependency @angular/material-moment-adapter @ "15.0.0" (was "14.2.7")...
UPDATE package.json (6305 bytes)
** Executing migrations of package '@angular/cdk' **
> Updates the Angular CDK to v15.
```

```
[error] Error: [91merror[0m[90m TS18003: [0mNo inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["src/**/*.d.ts"]' and 'exclude' paths were '["src/test.ts","**/*.spec.ts"]'.

    at parseTsconfigFile (C:\dev\monorepo\angular\node_modules\@angular\cdk\schematics\update-tool\utils\parse-tsconfig.js:41:15)
    at Function.createProgramFromTsconfig (C:\dev\monorepo\angular\node_modules\@angular\cdk\schematics\update-tool\index.js:172:63)
    at runMigrations (C:\dev\monorepo\angular\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:114:57)
    at C:\dev\monorepo\angular\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:85:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callRuleAsync (C:\dev\monorepo\angular\node_modules\@angular-devkit\schematics\src\rules\call.js:78:18)
```

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

cdk update schematics does not fail

### Actual Behavior

cdk update schematics fails

### Environment

- Angular: 15
- CDK/Material: 14
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by RobinKamps** [comment]
turns out to be not angular update / schematics related. 
tsconfig needs at least one empty file to be included, otherwise this error will show up.
