### ISSUE TITLE
docs-bug(Menu): "Testing with MatMenuHarness" example does not run in Chrome or Firefox

### ISSUE THREAD

**Issue by rms2219** [angular/components#26806]
### Documentation Feedback

When running the Stackblitz [example](https://material.angular.io/components/menu/examples#menu-harness), there is an error, and the tests do not run:

```
Chrome 111.0.0.0 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  TypeError: __webpack_require__(...).context is not a function
      at Object.4289 (https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/main.js:123:42)
      at __webpack_require__ (https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/runtime.js:23:41)
      at __webpack_exec__ (https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/main.js:160:48)
      at https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/main.js:161:54
      at Function.__webpack_require__.O (https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/runtime.js:57:23)
      at https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/main.js:162:56
      at webpackJsonpCallback (https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/runtime.js:140:39)
      at https://j4sbjmrun-ck3n--9876.local-credentialless.webcontainer.io/_karma_webpack_/main.js:1:75
Chrome 111.0.0.0 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0 secs / 0 secs)
```

### Affected documentation page

https://material.angular.io/components/menu/examples

**Comment by wagnermaciel** [comment]
I believe this may be a regression in stackblitz itself
