### ISSUE TITLE
mdc-migrations v15.2.5 not updating html for form-fields

### ISSUE THREAD

**Issue by raysuelzer** [angular/components#27531]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am trying to upgrade my v14 form fields to v15. When running the partial migration it changes 0 html files, leaving the app in a broken state with the error. 

Why is this not updating any html files? 

```
S > npx ng generate @angular/material:mdc-migration
? Limit the migration to a specific directory? (Enter the relative path such as 'src/app/shared' or leave blank for all directories)
? What components do you want to migrate? Form Field, Input, Select, Autocomplete
    Migrating components:
    form-field
    autocomplete
    input
    option
    optgroup
    select
    Migrating project: frontend
    Successfully migrated the project.
UPDATE src/app/upload/pages/upload-standard/upload-standard.page.scss (738 bytes)
UPDATE src/app/upload/pages/upload-delete-mode/upload-delete-mode.page.scss (319 bytes)
UPDATE src/app/uploads2/components/mapped-property-row/mapped-property-row.component.scss (472 bytes)
UPDATE src/app/uploads2/pages/upload-create/upload-create.page.scss (951 bytes)
....
```

This is the error I get. Note: I don't have "standard" used anywhere in the app. 
```
Error: MatFormField: Invalid appearance "standard", valid values are "fill" or "outline".
    at set appearance [as appearance] (form-field.mjs:499:23)
    at new MatFormField (form-field.mjs:569:32)
    at NodeInjectorFactory.MatFormField_Factory [as factory] (form-field.mjs:918:18)
    at getNodeInjectable (core.mjs:3447:44)
    at instantiateAllDirectives (core.mjs:11013:27)
    at createDirectivesInstances (core.mjs:10486:5)
    at ɵɵelementStart (core.mjs:13616:9)
    at SimpleQueryCanvassStatusInputComponent_Template (simple-query-canvass-status-input.component.html:1:6)
    at executeTemplate (core.mjs:10457:9)
    at renderView (core.mjs:10279:13)
```

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

The html to be migrated

### Actual Behavior

Only scss and ts files were migrated

### Environment

Angular: 15.2.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.2.4
@angular/cli                    15.2.4
@schematics/angular             15.2.4
rxjs                            7.5.6
typescript                      4.8.4

**Comment by raysuelzer** [comment]
Okay it sort of works now, it did not update my providers which set the default appearance options, so that's a problem.... It also is strange that 0 changes to the html files were made.
