### ISSUE TITLE
bug(COMPONENT): MatExpansionPanelHarness

### ISSUE THREAD

**Issue by FedeTommi** [angular/components#29454]
### Description

The filters on MatExpansionPanelHarness seem to be not working correctly.

### Reproduction

Run a test with the following content:

const expansionPanels = await loader.getHarness(MatExpansionPanelHarness.with({ disabled: true }));

### Expected Behavior

I get a list of MatExpansionPanelHarness that are disabled

### Actual Behavior

I get the error:

SyntaxError: '' is not a valid selector
    at emit (/node_modules/nwsapi/src/nwsapi.js:575:17)
    at Object._querySelectorAll [as select] (/node_modules/nwsapi/src/nwsapi.js:1491:9)
    at HTMLDivElementImpl.querySelectorAll (node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:78:26)
    at HTMLDivElement.querySelectorAll (node_modules/jsdom/lib/jsdom/living/generated/Element.js:1119:58)
    at Object.queryFn (node_modules/@angular/cdk/fesm2022/testing/testbed.mjs:622:39)
    at TestbedHarnessEnvironment.getAllRawElements (node_modules/@angular/cdk/fesm2022/testing/testbed.mjs:770:41)

### Environment

- Angular: 18.1.1
- CDK/Material: 18.1.1
- Browser(s): -
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment]
This sounds like an issue `nwsapi` which aims to reimplement CSS selectors in JS.
