### ISSUE TITLE
The error should be fixed by #28551 in the 17.2.0 release.

### ISSUE THREAD

**Issue by Khalil-IT** [angular/components#29704]
The error should be fixed by #28551 in the 17.2.0 release.

_Originally posted by @crisbeto in https://github.com/angular/components/issues/28626#issuecomment-1959427524_

i still get tha same error for this after upgrading
<code>
Angular CLI: 17.3.8
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cdk                    17.3.10
@angular/cli                    17.3.8
@angular/google-maps            17.0.1
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
</code>
<code>
ERROR NullInjectorError: R3InjectorError(_AppModule)[InjectionToken CDK_TABLE -> InjectionToken CDK_TABLE]: 
  NullInjectorError: No provider for InjectionToken CDK_TABLE!
    at NullInjector.get (core.mjs:1654:27)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at ChainedInjector.get (core.mjs:15723:36)
    at lookupTokenUsingModuleInjector (core.mjs:5730:39)
    at getOrCreateInjectable (core.mjs:5778:12)
    at ɵɵdirectiveInject (core.mjs:11050:19)
    at ɵɵinject (core.mjs:1106:42)
    at inject (core.mjs:1192:12)
    at new _HeaderRowOutlet (table.mjs:1528:19)
</code>

and i upgrade anguale-cdk to     "@angular/cdk": "^17.3.0",
and get the same error

**Comment by crisbeto** [comment]
This is likely an issue with your setup. This issue hasn't been reported on Github since #28551 or in any of our thousands internal applications. Refer to the docs to see how to set up your table: https://material.angular.io/components/table/overview
