### ISSUE TITLE
[v19] Migration failed: Failed to decode "/node_modules/needle/test/files/Appalachia.html" as UTF-8 text.

### ISSUE THREAD

**Issue by spock123** [angular/components#29917]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I am trying to install V19-next.11 (coming from V18).

Installation went smoothly with next-10 version, but trying next-11 I got the following errors during installation

### Please provide the exception or error you saw

```
UPDATE src/app/features/booking/booking-experience-guests/booking-experience-guests.component.ts (3842 bytes)
UPDATE src/app/app.component.ts (318 bytes)
UPDATE src/app/features/dashboard/widgets/widget-revenue/widget-revenue.component.ts (2034 bytes)
UPDATE src/app/features/dashboard/widgets/widget-revenue-today/widget-revenue-today.component.ts (927 bytes)
UPDATE src/app/features/dashboard/widgets/widget-template/widget-template.component.ts (1666 bytes)
  Migration completed (40 files modified).

❯ Updates ExperimentalPendingTasks to PendingTasks.
  Migration completed (No changes made).

** Optional migrations of package '@angular/core' **

This package has 1 optional migration that can be executed.
Optional migrations may be skipped and executed after the update process, if preferred.

 Select the migrations that you'd like to run [provide-initializer] Replaces `APP_INITIALIZER`,
'ENVIRONMENT_INITIALIZER' & 'PLATFORM_INITIALIZER' respectively with `provideAppInitializer`,
`provideEnvironmentInitializer` & `providePlatormInitializer`.

❯ Replaces `APP_INITIALIZER`, 'ENVIRONMENT_INITIALIZER' & 'PLATFORM_INITIALIZER' respectively with `provideAppInitializer`, `provideEnvironmentInitializer` & `providePlatormInitializer`.
  Migration completed (No changes made).

** Executing migrations of package '@angular/google-maps' **

❯ Updates the Angular Google Maps package to v19.
✖ Migration failed: Failed to decode "/node_modules/needle/test/files/Appalachia.html" as UTF-8 text.
  See "/private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/ng-nMHh7y/angular-errors.log" for further details.
```

### Anything else?

Content of angular-errors.log:

```
[error] Error: Failed to decode "/node_modules/needle/test/files/Appalachia.html" as UTF-8 text.
    at HostTree.readText (/private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/angular-cli-packages-u0uCI8/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:232:23)
    at /Users/spock/projects/fresto/apps/analytics/node_modules/@angular/google-maps/schematics/ng-update/index_bundled.js:41:30
    at /private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/angular-cli-packages-u0uCI8/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:279:13
    at /private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/angular-cli-packages-u0uCI8/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:49:61
    at Array.forEach (<anonymous>)
    at HostDirEntry.visit (/private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/angular-cli-packages-u0uCI8/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:49:43)
    at HostTree.visit (/private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/angular-cli-packages-u0uCI8/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:278:19)
    at /Users/spock/projects/fresto/apps/analytics/node_modules/@angular/google-maps/schematics/ng-update/index_bundled.js:39:10
    at callRuleAsync (/private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/angular-cli-packages-u0uCI8/node_modules/@angular-devkit/schematics/src/rules/call.js:77:24)
    at /private/var/folders/3d/q3t4z_pn7zjb79mjb_mvqf140000gn/T/angular-cli-packages-u0uCI8/node_modules/@angular-devkit/schematics/src/rules/call.js:73:40
```

**Comment by JeanMeche** [comment]
Moving this to the components repo as this is a maps migration that is having an issue.

**Comment by spock123** [comment]
@JeanMeche  you're right, sorry bout that. Thanks for moving it.
