### ISSUE TITLE
docs-bug: styling tab broken

### ISSUE THREAD

**Issue by json-derulo** [angular/components#29965]
### Documentation Feedback

The newly added "Styling" tab is broken currently. A few hours ago it worked fine, but now when navigating to the "Styling" tab of any component, instead of the content only the following text is displayed:

> This component does not support style overrides

In the browser console, the following error is printed once the "Styling" tab is opened:

```
main.690dc78a22be8e65.js:1 ERROR TypeError: g.find is not a function
    at 5862.c72688d4f30e63c6.js:1:21144
    at main.690dc78a22be8e65.js:1:112617
    at R._next (main.690dc78a22be8e65.js:1:109247)
    at R.next (main.690dc78a22be8e65.js:1:98554)
    at subscribe.H (main.690dc78a22be8e65.js:1:116016)
    at R._next (main.690dc78a22be8e65.js:1:109247)
    at R.next (main.690dc78a22be8e65.js:1:98554)
    at R._subscribe (main.690dc78a22be8e65.js:1:95468)
    at R._trySubscribe (main.690dc78a22be8e65.js:1:94215)
    at R._trySubscribe (main.690dc78a22be8e65.js:1:97001)
```

Looks like #29964 might have broken it.

### Affected documentation page

https://rc.material.angular.io/components/checkbox/styling

**Comment by json-derulo** [comment]
There was a new commit & deployment, and for now it seems to work fine again. next version also looks good.
