### ISSUE TITLE
"✖ Migration failed: <css input>:73:2: Unclosed string" While updating Angular Material v18 to v19

### ISSUE THREAD

**Issue by Raphyyy** [angular/components#30115]
### Command

update

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18

### Description

While performing the update migration from Angular Material v18 to v19 I am running through an error that I am not capable to debug : 
```
> ng update @angular/material --from 18 --to 19 --migrate-only
Using package manager: npm
Collecting installed dependencies...
Found 97 dependencies.
** Executing migrations of package '@angular/material' **

❯ Updates Angular Material to v19.
✖ Migration failed: <css input>:73:2: Unclosed string
  See "C:\Users\Raphael\AppData\Local\Temp\ng-ZlQfqb\angular-errors.log" for further details.
```

The `angular-errors.log` file :
```
[error] CssSyntaxError: <css input>:73:2: Unclosed string
    at Input.error (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:4080:20)
    at unclosed (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:6770:21)
    at Object.nextToken (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:6883:17)
    at ScssParser.other (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:5625:34)
    at ScssParser.parse (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:5669:20)
    at scssParse (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:7199:14)
    at new LazyResult (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:5952:20)
    at Processor.process (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:6487:18)
    at MatCoreMigration2.visitStylesheet (\node_modules\@angular\material\schematics\ng-update\index_bundled.js:7242:19)
    at \node_modules\@angular\cdk\schematics\update-tool\index.js:130:51
    at Array.forEach (<anonymous>)
    at \node_modules\@angular\cdk\schematics\update-tool\index.js:130:36
    at Array.forEach (<anonymous>)
    at UpdateProject.migrate (\node_modules\@angular\cdk\schematics\update-tool\index.js:124:39)
    at runMigrations (\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:121:42)
    at \node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:84:17
```

I removed any sass deprecated usage

### Minimal Reproduction

ng update @angular/material --from 18 --to 19 --migrate-only

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 19.0.2
Node: 22.11.0
Package Manager: npm 8.18.0
OS: win32 x64

Angular: 19.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-date-fns-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            18.2.7
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            6.5.5
typescript                      5.5.4
zone.js                         0.15.0
```

### Anything else relevant?

`ng build` doesn't produce any error.

**Comment by crisbeto** [comment]
Can you post the template that the migration is failing for?

**Comment by Raphyyy** [comment]
What template are you referring to ?

**Comment by crisbeto** [comment]
Ah nevermind, it looks like the migration failed to parse some syntax in a CSS file.
